version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: caruser
      POSTGRES_PASSWORD: carpassword
      POSTGRES_DB: cardb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  backend:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./app:/app/app
    environment:
      - DATABASE_URL=postgresql+asyncpg://caruser:carpassword@db:5432/cardb
      # Add other env vars here
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  pgdata:
